services:
  backend:
    build: ./backend
    container_name: z3-backend
    volumes:
      - ./backend:/app
    command: "fastapi dev src/app.py --host 0.0.0.0 --port 80"
    environment:
      REDIS_URL: redis://redis:6379
    expose:
      - "80"
    networks:
      - internal
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: deps
    container_name: z3-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host --port 3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    expose:
      - "3000"
    networks:
      - internal
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: z3-redis
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - internal
    restart: unless-stopped

  gateway:
    image: nginx:alpine
    container_name: z3-gateway
    depends_on:
      - frontend
      - backend
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
    ports:
      - "8001:80"
      # - "443:443"
    restart: unless-stopped

networks:
  internal:
    driver: bridge

volumes:
  redis-data: