services:
  backend:
    build: ./backend
    container_name: z3-backend
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
    expose:
      - "80"
    networks:
      - internal
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: z3-frontend
    depends_on:
      - backend
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    networks:
      - internal
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: z3-redis
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - internal
    restart: unless-stopped

  gateway:
    image: nginx:alpine
    container_name: z3-gateway
    depends_on:
      - frontend
      - backend
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
    ports:
      - "80:80"
      # - "10.7.0.1:34568:80"
      # - "443:443"
    restart: unless-stopped

networks:
  internal:
    driver: bridge

volumes:
  redis-data: